import Navbar from './Navbar';

const About = () => {    
    return (
        <div>
            <Navbar />
            <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Vitae purus faucibus ornare suspendisse sed nisi lacus. Ac ut consequat semper viverra nam libero. Viverra orci sagittis eu volutpat odio facilisis mauris. Sem integer vitae justo eget magna fermentum iaculis eu. Nibh sed pulvinar proin gravida. Erat nam at lectus urna duis convallis convallis tellus id. In hac habitasse platea dictumst quisque sagittis purus sit. Velit ut tortor pretium viverra. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Feugiat scelerisque varius morbi enim. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Hendrerit gravida rutrum quisque non tellus orci ac.</p>
            <p>Platea dictumst vestibulum rhoncus est. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Vel facilisis volutpat est velit. Sit amet nisl suscipit adipiscing. Quis varius quam quisque id diam vel. Interdum consectetur libero id faucibus nisl tincidunt eget. Arcu ac tortor dignissim convallis aenean. Non odio euismod lacinia at quis. Est ultricies integer quis auctor elit. Sapien et ligula ullamcorper malesuada proin libero nunc.</p>
            <p>Eget nullam non nisi est sit amet facilisis magna. Integer vitae justo eget magna fermentum iaculis eu. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Arcu dictum varius duis at consectetur. Id leo in vitae turpis massa sed. Bibendum enim facilisis gravida neque. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Eget arcu dictum varius duis at consectetur lorem. Natoque penatibus et magnis dis parturient montes nascetur. Euismod lacinia at quis risus sed vulputate. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Purus gravida quis blandit turpis cursus in. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Quisque sagittis purus sit amet volutpat. Id diam vel quam elementum pulvinar etiam.</p>
            <p>Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Turpis egestas maecenas pharetra convallis posuere morbi. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Congue quisque egestas diam in arcu cursus euismod. Dolor sit amet consectetur adipiscing elit ut. Turpis egestas sed tempus urna. Congue mauris rhoncus aenean vel elit. Massa tempor nec feugiat nisl pretium fusce id velit ut. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Elit at imperdiet dui accumsan sit amet nulla facilisi. Dis parturient montes nascetur ridiculus mus mauris. Facilisis volutpat est velit egestas dui id ornare arcu odio. Fringilla est ullamcorper eget nulla. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Sapien eget mi proin sed libero enim sed faucibus turpis.</p>
            <p>Nec tincidunt praesent semper feugiat nibh. Neque vitae tempus quam pellentesque nec. Morbi tristique senectus et netus et malesuada fames. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Amet venenatis urna cursus eget nunc scelerisque viverra mauris. Accumsan tortor posuere ac ut consequat semper viverra nam. Nisi vitae suscipit tellus mauris a. Eros donec ac odio tempor orci. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Auctor augue mauris augue neque gravida. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Ut tortor pretium viverra suspendisse. Eu nisl nunc mi ipsum faucibus. At auctor urna nunc id cursus metus aliquam eleifend mi. Sed nisi lacus sed viverra tellus in hac habitasse. Eu lobortis elementum nibh tellus molestie nunc non. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ac turpis egestas integer eget. Nisl purus in mollis nunc sed id semper. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.</p>
            </div>
        </div>
    )
}

export default About